# Generated by Django 5.1.6 on 2025-02-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_task_is_deleted_alter_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
